### ISSUE TITLE
Wrong behavior with pipes from other mods

### ISSUE THREAD

**Issue by CrossVas** [Nukepowered/GregTech4#117]
Every machine that has auto-output option will behave like this when pipes from other mods are used (tried with EIO and TE pipes, the same result). 
It works great with chests and GT pipes, but it would be great to have this fixed for other pipes as well.

Demo: https://imgur.com/a/ZuDBTP0

And this is the result if you leave it for like 5 minutes: 
![image](https://user-images.githubusercontent.com/25727222/117006369-04a5c280-acf1-11eb-8672-5909d77eef9a.png)

**Comment by TheDarkDnKTv** [comment]
```
[Server thread/ERROR] [GregTech/]: Encountered Exception while ticking MetaTileEntity, the Game should've crashed now, but I prevented that. Please report immidietly to GregTech Intergalactical!!!
[Server thread/ERROR] [GregTech/]: catching
java.lang.NullPointerException
	at gregtechmod.api.util.GT_Utility.moveStackIntoPipe(GT_Utility.java:418) ~[GT_Utility.class:?]
	at gregtechmod.api.util.GT_Utility.moveOneItemStack(GT_Utility.java:585) ~[GT_Utility.class:?]
	at gregtechmod.api.util.GT_Utility.moveOneItemStack(GT_Utility.java:514) ~[GT_Utility.class:?]
	at gregtechmod.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine.onPostTick(GT_MetaTileEntity_BasicMachine.java:121) ~[GT_MetaTileEntity_BasicMachine.class:?]
	at gregtechmod.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:464) [BaseMetaTileEntity.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2583) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by CrossVas** [comment]
Big ooof. My bad, should have provide the log.
